const ADD_RSS = 'ADD_RSS';
const UPDATE_RSS = 'UPDATE_RSS';
const ERROR = 'ERROR';
const TRIGGER_SAVE = 'TRIGGER_SAVE';
const RESET_ADD_FROM = 'RESET_ADD_FROM';
const GET_RSS_ITEM = 'GET_RSS_ITEM';
const DELETE_RSS_FEED = 'DELETE_RSS_FEED';
const RSS_FETCH_START = 'RSS_FETCH_START';
const RSS_FETCH_FAIL = 'RSS_FETCH_FAIL';
const RSS_FETCH_SUCCESS = 'RSS_FETCH_SUCCESS';
const DUPLICATED_FEED = 'DUPLICATED_FEED';

export {
    ADD_RSS,
    UPDATE_RSS,
    ERROR,
    TRIGGER_SAVE,
    RESET_ADD_FROM,
    GET_RSS_ITEM,
    DELETE_RSS_FEED,
    RSS_FETCH_START,
    RSS_FETCH_FAIL,
    RSS_FETCH_SUCCESS,
    DUPLICATED_FEED
};
