const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';
const ERROR = 'ERROR';
const TRIGGER_SAVE = 'TRIGGER_SAVE';
const RESET_ADD_FROM = 'RESET_ADD_FROM';
const GET_RSS_ITEM = 'GET_RSS_ITEM';

module.exports = {
    VALIDATION_SUCCESS,
    ERROR,
    TRIGGER_SAVE,
    RESET_ADD_FROM,
    GET_RSS_ITEM
};
